### ISSUE TITLE
As a registered student, I would like to receive notifications of different events going on campus that are held in my free time, so that I can attend them if I wish.

### ISSUE THREAD

**Issue by camilacampos** [camilacampos/EventMasterApp#3]

**Comment by dvb3000** [comment]
Would it make more sense to say "I would like" instead of "I need"?

**Comment by camilacampos** [comment]
On the main page, the list of events that the student might be interested in could be similar to one of these:

![agenda](https://cloud.githubusercontent.com/assets/2309096/4854710/cfd3a9b6-6097-11e4-8e9a-404cc9ea9e6b.png)

![agenda2](https://cloud.githubusercontent.com/assets/2309096/4854721/fceb1ad8-6097-11e4-82c6-c28efb6a8388.png)

**Comment by camilacampos** [comment]
Also, when clicking on the event, the details could be similar to this one: 

![eventdetails](https://cloud.githubusercontent.com/assets/2309096/4854725/12ccc572-6098-11e4-86bb-a769fb09c5a6.png)
